### ISSUE TITLE
Full As3 API supported?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [johnbrandle/as3-js#1]
Hello,
does it support all AS3 API?
thanks

**Comment by johnbrandle** [comment]
I will be creating documentation in the coming weeks, as well as examples, and unit tests (hopefully) that should better answer your question. However, for now I would say:

Support for the Flash API and E4X is limited. Most of the important bits of the Flash API work, and very close (if not exactly) as it would in the Flash Player (bugs intentionally included). Notable exceptions are Display3D, describeType, and MovieClip (limited, using: http://gree.github.io/lwf/). Pure AS3 projects that do not make use of these features tend to port over without much issue.

**Comment by ROBERT-MCDOWELL** [comment]
John, you should reference your repo here
https://github.com/open-source-flash/open-source-flash
does it support the p2p, mutlicast and netgroup classes?

**Comment by johnbrandle** [comment]
Thanks. No, mostly DisplayList and utility related classes are implemented, see here: https://github.com/johnbrandle/as3-js/tree/master/_excluded/playerglobal
